---
- name: write the config files for kubelet
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  when: not kubelet_use_pre_v10_vars
  notify:
          - restart kubelet

- include: kubelet-old.yaml
  when: kubelet_use_pre_v10_vars

- name: write the config files for proxy
  template: src=proxy.j2 dest=/etc/kubernetes/proxy
  notify:
          - restart proxy

- name: Enable kubelet
  service: name=kubelet enabled=yes state=started

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started
