---
- include: centos7.yml
  when: is_centos7.rc == 0

- name: write the global config file
  template: src=config.j2 dest=/etc/kubernetes/config

- name: collect facts about the version of kubernetes
  kube-caps:
